# Site settings
title:          Shawn Roos
description:    "Product Person Based in Cape Town South Africa "
baseurl:        ""
url:            "jeylhttps://shawnroos.com"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Shawn Roos
  url:          127.0.0.1:4000/shawnroos/
  email:        shawn.roos@gmail.com

# Build settings
markdown: kramdown
include: 
- _pages
- _posts

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       10

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         